context:
  name: pixi-inject
  version: "0.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/pavelzw/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 041dfb98924bf925d8a47f8cc075b0a26a8a9caa7cecf4d957d7793d52108a17

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - if: unix
      then: openssl

tests:
  - script:
      - pixi-inject --help

about:
  homepage: https://github.com/pavelzw/pixi-inject
  summary: Inject conda packages into an already existing conda prefix
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/pavelzw/pixi-inject

extra:
  recipe-maintainers:
    - pavelzw
